### ISSUE TITLE
MacOS build failing

### ISSUE THREAD

**Issue by kkCoder111** [BlossomiShymae/barcodes#4]
A quick look at the actions tag shows that the macOS build is failing. Looks like due to a clang error.

![image](https://github.com/user-attachments/assets/0d3914ef-3227-4a2b-98fb-ad163881d220)

**Comment by BlossomiShymae** [comment]
This issue seems to be the reason.
https://github.com/rust-build/rust-build.action/issues/88

I'll see if I can update the workflow that doesn't use this action.

**Comment by BlossomiShymae** [comment]
Should be fixed within https://github.com/BlossomiShymae/barcodes/compare/0.2.1...0.3.0. Let me know if there are any issues. :>
